# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f448178d10579045e35f7b9616ee8946"
name = "checkout-ui"
handle = "checkout-ui-309"
application_url = "https://couples-pj-emotions-wheel.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkoutextension2024.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://couples-pj-emotions-wheel.trycloudflare.com/auth/callback",
  "https://couples-pj-emotions-wheel.trycloudflare.com/auth/shopify/callback",
  "https://couples-pj-emotions-wheel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
